name: Automating Image Push to Docker HUB

on:
  push:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Log in to Docker HUB
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Publish Docker Image
        run: |
          registry="mubashirhusain005"
          sha=$(git rev-parse --short HEAD)
          primary_tag="${registry}/cicd-test:${sha}"

          echo "Building Docker image $primary_tag"
          docker build -t $primary_tag -f Dockerfile .

          echo "Pushing Docker image $primary_tag"
          docker push $primary_tag

          current_branch=$(git rev-parse --abbrev-ref HEAD)
          if [ "$current_branch" = "main" ]; then
            retention_tag="${registry}/cicd-test:rc-${sha}"
            echo "Tagging image as $retention_tag"
            docker tag $primary_tag $retention_tag
            docker push $retention_tag
          fi
