name: CoderCo Custom Action CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Hello world custom action 
        uses: MubashirHusain2005/coderco-custom-@main
        with:
          who-to-greet: 'CoderCo Team'

#Trigger re-run